#!/bin/bash
cp $1 ./
file=$(basename "$1")
mv "$file" "${file%.epub}.zip"
unzip "${file%.epub}.zip" -d "${file%.epub}"
#ln -s "${file%.epub}/OEBPS/images/" images
#mkdir images
mv ${file%.epub}/OEBPS/images/* ../images/
rm "${file%.epub}.zip"
find ./ -type d -mtime +1 -delete
find ../images/ -type f -mtime +1 -delete

