#!/bin/bash
##
# Copyright (c) 2013 Andrea Bernardini.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##

cp $1 ./
file=$(basename "$1")
mv "$file" "${file%.epub}.zip"
unzip "${file%.epub}.zip" -d "${file%.epub}"
#ln -s "${file%.epub}/OEBPS/images/" images
#mkdir images
mv ${file%.epub}/OEBPS/images/* ../images/
rm "${file%.epub}.zip"
find ./ -type d -mtime +1 -delete
find ../images/ -type f -mtime +1 -delete

