Default: &defaults
  user: newsprint
  password: yourpassword
  host: localhost
  port: 3306
  database: NewsPrintAM
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: NewsPrint_test
  <<: *defaults

Staging:
  database: NewsPrint_staging
  poolsize: 100
  <<: *defaults

Production:
  database: NewsPrint_production
  poolsize: 100
  <<: *defaults
