Default: &defaults
  user: NewsPrint
  password: NewsPrint
  host: localhost
  port: 5432
  database: NewsPrint
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: NewsPrint_test
  <<: *defaults

Staging:
  database: NewsPrint_staging
  poolsize: 100
  <<: *defaults

Production:
  database: NewsPrint_production
  poolsize: 100
  <<: *defaults
